remote_theme : niklasbuschmann/contrast@v3.0
plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-seo-tag

name: Sceneform Maintained SDK for Android
title: Sceneform Maintained SDK for Android
show_title: false
description: "Sceneform is a 3D framework with a physically based renderer that's optimized for mobile devices and that makes it easy for you to build Augmented Reality (AR) apps without requiring OpenGL or Unity."
markdown: GFM

show_sidebar: false

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.md", icon: "/images/icons/menu/home.svg"}
  - {title: "Github", url: "https://github.com/ThomasGorisse/sceneform-android-sdk", icon: "/images/icons/menu/github.png"}
  - {title: "Dependencies", url: "/#dependencies", icon: "/images/icons/menu/download.svg"}
  - {title: "Usage", url: "/#basic-usage-simple-model-viewer", icon: "/images/icons/menu/code.svg"}
  - {title: "Samples", url: "/#samples", icon: "/images/icons/menu/view_in_ar.svg"}
  - {title: "Emulator", url: "/#emulator", icon: "/images/icons/menu/smartphone.svg"}
  - {title: "Documentation", url: "/#go-further", icon: "/images/icons/menu/book.svg"}
  - {title: "Sponsor", url: "https://github.com/sponsors/ThomasGorisse", icon: "/images/icons/menu/favorite.svg"}
  - {title: "Javadoc", url: "/javadoc/index.html", icon: "/images/icons/menu/api.svg"}

external:
  - {title: Github, icon: github, url: "https://github.com/ThomasGorisse/sceneform-android-sdk"}
