remote_theme : niklasbuschmann/contrast@v3.0
plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-remote-theme

title: Sceneform Maintained SDK for Android
permalink: /:title/
show_title: false
show_description: false
description: "Sceneform is a 3D framework with a physically based renderer that's optimized for mobile devices and that makes it easy for you to build Augmented Reality (AR) apps without requiring OpenGL or Unity."
markdown: GFM
dark_header: false
minimal: true
sidebar: false

show_sidebar: false

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.md", icon: home}
  - {title: "Github", url: "https://github.com/ThomasGorisse/sceneform-android-sdk", icon: github}
  - {title: "Dependencies", url: "/#dependencies", icon: download}
  - {title: "Usage", url: "/#basic-usage-simple-model-viewer", icon: code}
  - {title: "Samples", url: "/#samples", icon: view_in_ar}
  - {title: "Emulator", url: "/#emulator", icon: smartphone}
  - {title: "Documentation", url: "/#go-further", icon: book}
  - {title: "Sponsor", url: "https://github.com/sponsors/ThomasGorisse", icon: favorite}
  - {title: "Javadoc", url: "/javadoc/index.html", icon: api}

external:
  - {title: Github, icon: github, url: "https://github.com/ThomasGorisse/sceneform-android-sdk"}
